import 'package:notification_demo/models/product_info_model.dart';

List<ProductInfoModel> dummyModel = [
  ProductInfoModel(
    id: 1,
    productName: "name 1",
    offerPrice: 122,
    originalPrice: 23,
    productDescription: "this is description 1 ",
    productImage: "/",
    shopName: "shop 1 ",
  ),
  ProductInfoModel(
    id: 2,
    productName: "name 2",
    offerPrice: 1234,
    originalPrice: 234,
    productDescription: "this is description 2 ",
    productImage: "/",
    shopName: "shop 3 ",
  ),
  ProductInfoModel(
    id: 1,
    productName: "name 3",
    offerPrice: 122,
    originalPrice: 23,
    productDescription: "this is description 3 ",
    productImage: "/",
    shopName: "shop 1 ",
  ),
  ProductInfoModel(
    id: 1,
    productName: "name 4",
    offerPrice: 122,
    originalPrice: 23,
    productDescription: "this is description 4",
    productImage: "/",
    shopName: "shop 4 ",
  ),
  ProductInfoModel(
    id: 1,
    productName: "name 5",
    offerPrice: 122,
    originalPrice: 23,
    productDescription: "this is description 5 ",
    productImage: "/",
    shopName: "shop 5",
  ),
  ProductInfoModel(
    id: 1,
    productName: "name 6",
    offerPrice: 1224,
    originalPrice: 235,
    productDescription: "this is description 6 ",
    productImage: "/",
    shopName: "shop 6 ",
  ),
  ProductInfoModel(
    id: 1,
    productName: "name 7",
    offerPrice: 1233,
    originalPrice: 266,
    productDescription: "this is description 7 ",
    productImage: "/",
    shopName: "shop 1 ",
  )
];
